<?php

/**   
 * Implements hook_init().
 */ 
function spcivipush_init() {
  module_load_include("inc", "spcivipush", "spcivipush");
}   

/*
 * Push contact to CiviCRM.
 *
 * data: array()
 *   keys:
 *     - contact_id
 *     - name
 *     - first_name
 *     - middle_name
 *     - last_name
 *     - email
 *     - telephone
 *     - street
 *     - house_number
 *     - house_number_addition
 *     - street_and_number
 *     - postal_code
 *     - locality
 *     - note
 *         content
 *         use
 *     - overwrite
 *     - author
 *     - source
 *     - groups: array(group_id_1, group_id_2, etc.)
 *
 *
 * debug_info: variable content shown in logs.
 *
 */
function spcivipush_push_contact($data, $debug_info) {
  // Cleanup data.
  $data = spcivipush_parse_data($data);
  // Check if submission contains data nescesarry to create contact.
  if (spcivipush_check_submission_sufficient($data)) {
    // Sync contact.
    $contact_id = spcivipush_sync_contact($data, $debug_info);
    if (!empty($contact_id)) {
      return $contact_id;
    }
    else {
      return FALSE;
    }
  }
  else {
    return 'insufficient data';
  }
}

/**
 * Implements hook_menu().
 */
function spcivipush_menu() {
  $items = array();

  $items['admin/config/sp/spcivipush'] = array(
    'title' => 'SP Civipush',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spcivipush_settings_form'),
    'file' => 'spcivipush.admin.inc',
    'access callback' => 'sprbs_access_check',
  );

  $items['admin/config/sp/spcivipush/settings'] = array(
    'title' => 'Instellingen',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'sprbs_access_check',
    'weight' => '0',
  );

  return $items;
}

function spcivipush_mail($key, &$message, $params) {
  switch ($key) {
  case 'manual_merge':
    $message['subject'] = 'Handmatig mergen CiviCRM contact';
    $message['body'][] = 'Beste,';
    $message['body'][] = 'het volgende contact is via een automatische synchronizatie toegevoegd in CiviCRM. Dit contact moet handmatig worden samengevoegd met reeds bestaande contacten. Komt dit bericht onnodig voor, en had het contact automatisch samengevoegd kunnen worden, laat het dan weten aan het webteam.';
    $message['body'][] = 'CiviCRM contact id: ' . $params['contact_id'];
    $message['body'][] = 'Thx, het webteam';
    $message['body'][] = '(Dit is een automatisch gegenereerd bericht).';
    break;
  case 'check_name':
    $message['subject'] = 'Handmatig controleren naam CiviCRM contact';
    $message['body'][] = 'Beste,';
    $message['body'][] = 'het volgende contact is via een automatische synchronizatie toegevoegd in CiviCRM. De naam van dit contact moet helaas handmatig worden gecorrigeerd. Komt dit te vaak voor, of onnodig, laat het dan aan het webteam weten.';
    $message['body'][] = 'CiviCRM contact id: ' . $params['contact_id'];
    $message['body'][] = 'Te corrigeren naam: "' . $params['name'] . '"';
    $message['body'][] = 'Thx, het webteam';
    $message['body'][] = '(Dit is een automatisch gegenereerd bericht).';
    break;
  case 'check_address':
    $message['subject'] = 'Handmatig controleren adres CiviCRM contact';
    $message['body'][] = 'Beste,';
    $message['body'][] = 'het volgende contact is via een automatische synchronizatie toegevoegd in CiviCRM. Het adres van dit contact moet helaas handmatig worden gecontroleerd. Komt dit te vaak voor, of onnodig, laat het dan aan het webteam weten.';
    $message['body'][] = 'CiviCRM contact id: ' . $params['contact_id'];
    switch ($params['type']) {
    case 'multiple_address_check':
      $message['body'][] = 'Er zijn meerdere adressen, mogelijk moet e.e.a. opgeschoond.';
      break;
    case 'house_number_addition_check':
      $message['body'][] = 'Te controleren adres: "' . $params['street_and_number'] . '"';
      break;
    }
    $message['body'][] = 'Thx, het webteam';
    $message['body'][] = '(Dit is een automatisch gegenereerd bericht).';
    break;
  }
}
