<?php

/**
 * Implements hook_init().
 */
function spcivipush_init() {
  module_load_include("inc", "spcivipush", "spcivipush");
}

/*
 * Push contact to CiviCRM.
 *
 * data: array()
 *   keys:
 *     - contact_id
 *     - name
 *     - first_name
 *     - middle_name
 *     - last_name
 *     - initials
 *     - birth_date (1974-01-28)
 *     - gender (m,v,a)
 *     - email
 *     - telephone
 *     - phone_mobile
 *     - street
 *     - house_number
 *     - house_number_addition
 *     - street_and_number
 *     - postal_code
 *     - locality
 *     - country (NL)
 *     - notes: array(
 *         array(
 *           note_content,
 *           note_use: array(
 *             intern
 *           )
 *         )
 *         array(
 *           note_content
 *           note_use: array(
 *           )
 *         )
 *         ...
 *       )
 *     - overwrite
 *     - author
 *     - source
 *     - groups: array(group_id_1, group_id_2, etc.)
 *     - sp_active: array(
 *         active,
 *         activities: array(
 *         )
 *       )
 *
 *
 * debug_info: variable content shown in logs.
 *
 */
function spcivipush_push_contact($data, $debug_info) {
  if (
    // Check if testing.
    (empty($data['name']) || strpos(strtolower($data['name']), '-test') === FALSE) &&
    (empty($data['first_name']) || strpos(strtolower($data['first_name']), '-test') === FALSE) &&
    (empty($data['last_name']) || strpos(strtolower($data['last_name']), '-test') === FALSE)
  ) {
    $time_start = microtime(true);
    // Cleanup data.
    $data = spcivipush_parse_data($data);
    // Check if submission contains data nescesarry to create contact.
    if (spcivipush_check_submission_sufficient($data)) {
      // Sync contact.
      $contact_id = spcivipush_sync_contact($data, $debug_info);
      if (!empty($contact_id)) {
        $time_end = microtime(true);
        watchdog('spcivipush', 'Process time: ' . ($time_end - $time_start));
        return $contact_id;
      }
      else {
        return FALSE;
      }
    }
    else {
      return 'insufficient data';
    }
  }
  else {
    drupal_set_message('Test data, not sending to CiviCRM');
    return 'insufficient data';
  }
}

/**
 * Implements hook_menu().
 */
function spcivipush_menu() {
  $items = array();

  $items['admin/config/sp/spcivipush'] = array(
    'title' => 'SP Civipush',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spcivipush_settings_form'),
    'file' => 'spcivipush.admin.inc',
    'access callback' => 'sprbs_access_check',
  );

  $items['admin/config/sp/spcivipush/settings'] = array(
    'title' => 'Instellingen',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => 'sprbs_access_check',
    'weight' => '0',
  );

  return $items;
}
